[package]
name = "my_first_azul_app"
version = "0.1.0"
authors = ["Tomohide Takao <amakunai.dorayaki@gmail.com>"]
edition = "2018"

[dependencies]
azul = { git = "https://github.com/maps4print/azul" }